# -*- coding: utf-8 -*-
"""Arithmetic_operation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/169-sOwaPUr9U7HW_PeTjtUyfnotiv3Bu
"""

x = 12
y = 6
print(x+y)
print(x-y)
print(x*y)
print(x/y)

print(x^y)

