# -*- coding: utf-8 -*-
"""Dict's_builtin_functions .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pbYKIkw2OhOXEwcNYJHJvEv5P10Eshxj
"""

marks ={"lang1":98,"lang2":67,"Maths":93,"Science":88}
print(marks)
marks.get("Maths")

marks.values()

marks.items()

marks.keys()

marks.fromkeys("Maths")

