# -*- coding: utf-8 -*-
"""List's_builtin_functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aT2sK0PgNeafoIG_GRPakZckJYJViCLz
"""

l=[98,85,67,79,90]
print(l)
l.append(100)
print(l)

l.insert(2,80)
print(l)

l.index(98)

l.count(79)

l.pop(2)
print(l)

l.clear()
print(l)